export const KEYDOWN_EVENT = "keydown"
export const KEYUP_EVENT = "keyup"
export const SHIFT_KEY = "Shift"
export const SELECTION_COLOR = '#FFD700'
export const HIGHLIGHT_COLOR = 'rgba(0, 255, 0, 0.3)'
export const DEFAULT_CIRCLE_RADIUS = 50
export const NEW_SHAPE_COLOR = "#000000"
export const CANVAS_WIDTH = 500
export const CANVAS_HEIGHT = 500